meta_product_name: "Mise en place"
meta_title: "Mise en place - Cooking made easy"
meta_description: "Have a nice experience cooking"
meta_image: "cover.png"
twitter_account: "@product_twitter_account"   # required for Twitter Cards
