meta_product_name: "Mise en place"
meta_title: "Mise en place - Cooking made easy"
meta_description: "Relevant description"
# meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
